// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOJt6fTTZa1uqpXmWHQ3kSYJolSwztiY',
    appId: '1:319215265890:web:cbe95689238bd27eb0493b',
    messagingSenderId: '319215265890',
    projectId: 'shopping-cart-df7a6',
    authDomain: 'shopping-cart-df7a6.firebaseapp.com',
    databaseURL: 'https://shopping-cart-df7a6-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-cart-df7a6.appspot.com',
    measurementId: 'G-HET2GSCXZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA_S2Bw6FrQZ4EuWoDrPi145dzksIaCKI',
    appId: '1:319215265890:android:4f00aca6f392e4a7b0493b',
    messagingSenderId: '319215265890',
    projectId: 'shopping-cart-df7a6',
    databaseURL: 'https://shopping-cart-df7a6-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-cart-df7a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD9s9wEmYjVPjoIjRDomOJ7GbGnlsVyjw',
    appId: '1:319215265890:ios:98f4f374cec2b3e6b0493b',
    messagingSenderId: '319215265890',
    projectId: 'shopping-cart-df7a6',
    databaseURL: 'https://shopping-cart-df7a6-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-cart-df7a6.appspot.com',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD9s9wEmYjVPjoIjRDomOJ7GbGnlsVyjw',
    appId: '1:319215265890:ios:d3ff6446123dcbabb0493b',
    messagingSenderId: '319215265890',
    projectId: 'shopping-cart-df7a6',
    databaseURL: 'https://shopping-cart-df7a6-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-cart-df7a6.appspot.com',
    iosBundleId: 'com.example.shoppingCart.RunnerTests',
  );
}
